# Generated by Django 3.2 on 2021-06-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20210606_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtable',
            name='GSE',
            field=models.CharField(db_column='GSE', default='', max_length=255),
        ),
    ]
