# Generated by Django 3.2 on 2021-06-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_searchtable_gse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTableRNAseq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Log2FC', models.FloatField(db_column='Log2FC', null=True)),
                ('lfcSE', models.FloatField(db_column='lfcSE', null=True)),
                ('stat', models.FloatField(db_column='stat', null=True)),
                ('p_value', models.FloatField(db_column='pvalue', null=True)),
                ('padj', models.FloatField(db_column='padj', null=True)),
                ('ensembl', models.CharField(db_column='ensembl', max_length=255)),
                ('entrezgene_id', models.IntegerField(db_column='entrezgene_id', default='')),
                ('GeneName', models.CharField(db_column='GeneName', max_length=255)),
                ('CellLine', models.CharField(db_column='CellLine', default='', max_length=255)),
                ('GSE', models.CharField(db_column='GSE', default='', max_length=255)),
                ('Rep', models.IntegerField(db_column='Rep', default='')),
                ('Dose', models.FloatField(db_column='Dose', null=True)),
                ('Duration', models.CharField(db_column='Duration', default='', max_length=255)),
                ('minus_log10padj', models.FloatField(db_column='minus_log10padj', null=True)),
            ],
            options={
                'db_table': 'RNAseqData',
            },
        ),
    ]
