# Generated by Django 3.2 on 2021-07-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_searchtablernaseq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchtablernaseq',
            name='CellLine',
        ),
        migrations.RemoveField(
            model_name='searchtablernaseq',
            name='GeneName',
        ),
        migrations.RemoveField(
            model_name='searchtablernaseq',
            name='Log2FC',
        ),
        migrations.RemoveField(
            model_name='searchtablernaseq',
            name='Rep',
        ),
        migrations.RemoveField(
            model_name='searchtablernaseq',
            name='ensembl',
        ),
        migrations.RemoveField(
            model_name='searchtablernaseq',
            name='entrezgene_id',
        ),
        migrations.RemoveField(
            model_name='searchtablernaseq',
            name='lfcSE',
        ),
        migrations.RemoveField(
            model_name='searchtablernaseq',
            name='minus_log10padj',
        ),
        migrations.RemoveField(
            model_name='searchtablernaseq',
            name='p_value',
        ),
        migrations.RemoveField(
            model_name='searchtablernaseq',
            name='padj',
        ),
        migrations.RemoveField(
            model_name='searchtablernaseq',
            name='stat',
        ),
        migrations.AddField(
            model_name='searchtablernaseq',
            name='Cellline',
            field=models.CharField(db_column='Cellline', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='searchtablernaseq',
            name='chr_num',
            field=models.CharField(db_column='chr', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='searchtablernaseq',
            name='end',
            field=models.IntegerField(db_column='end', null=True),
        ),
        migrations.AddField(
            model_name='searchtablernaseq',
            name='peakid',
            field=models.CharField(db_column='peakid', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='searchtablernaseq',
            name='start',
            field=models.IntegerField(db_column='start', null=True),
        ),
        migrations.AlterModelTable(
            name='searchtablernaseq',
            table='ChipSeqData',
        ),
    ]
