# Generated by Django 3.2 on 2021-07-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_auto_20210730_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTableChipSeq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chr_num', models.CharField(db_column='chr', default='', max_length=255)),
                ('start', models.IntegerField(db_column='start', null=True)),
                ('end', models.IntegerField(db_column='end', null=True)),
                ('peakid', models.CharField(db_column='peakid', default='', max_length=255)),
                ('GSE', models.CharField(db_column='GSE', default='', max_length=255)),
                ('Cellline', models.CharField(db_column='Cellline', default='', max_length=255)),
                ('Duration', models.CharField(db_column='Duration', default='', max_length=255)),
                ('Dose', models.FloatField(db_column='Dose', null=True)),
            ],
            options={
                'db_table': 'ChipSeqData',
            },
        ),
        migrations.RemoveField(
            model_name='searchtablernaseq',
            name='Cellline',
        ),
        migrations.RemoveField(
            model_name='searchtablernaseq',
            name='chr_num',
        ),
        migrations.RemoveField(
            model_name='searchtablernaseq',
            name='end',
        ),
        migrations.RemoveField(
            model_name='searchtablernaseq',
            name='peakid',
        ),
        migrations.RemoveField(
            model_name='searchtablernaseq',
            name='start',
        ),
        migrations.AddField(
            model_name='searchtablernaseq',
            name='CellLine',
            field=models.CharField(db_column='CellLine', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='searchtablernaseq',
            name='GeneName',
            field=models.CharField(db_column='GeneName', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='searchtablernaseq',
            name='Log2FC',
            field=models.FloatField(db_column='Log2FC', null=True),
        ),
        migrations.AddField(
            model_name='searchtablernaseq',
            name='Rep',
            field=models.IntegerField(db_column='Rep', default=''),
        ),
        migrations.AddField(
            model_name='searchtablernaseq',
            name='ensembl',
            field=models.CharField(db_column='ensembl', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='searchtablernaseq',
            name='entrezgene_id',
            field=models.IntegerField(db_column='entrezgene_id', default=''),
        ),
        migrations.AddField(
            model_name='searchtablernaseq',
            name='lfcSE',
            field=models.FloatField(db_column='lfcSE', null=True),
        ),
        migrations.AddField(
            model_name='searchtablernaseq',
            name='minus_log10padj',
            field=models.FloatField(db_column='minus_log10padj', null=True),
        ),
        migrations.AddField(
            model_name='searchtablernaseq',
            name='p_value',
            field=models.FloatField(db_column='pvalue', null=True),
        ),
        migrations.AddField(
            model_name='searchtablernaseq',
            name='padj',
            field=models.FloatField(db_column='padj', null=True),
        ),
        migrations.AddField(
            model_name='searchtablernaseq',
            name='stat',
            field=models.FloatField(db_column='stat', null=True),
        ),
        migrations.AlterModelTable(
            name='searchtablernaseq',
            table='RNAseqData',
        ),
    ]
