# Generated by Django 3.2 on 2021-07-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_auto_20210730_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTableChipSeqRefData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chr_num', models.CharField(db_column='chr', default='', max_length=255)),
                ('tss', models.IntegerField(db_column='tss', null=True)),
                ('tss_s', models.IntegerField(db_column='tss_s', null=True)),
                ('tss_e', models.IntegerField(db_column='tss_e', null=True)),
                ('generef', models.CharField(db_column='generef', default='', max_length=255)),
                ('gene', models.CharField(db_column='gene', default='', max_length=255)),
                ('strand', models.CharField(db_column='strand', default='', max_length=255)),
            ],
            options={
                'db_table': 'ChipseqReference',
            },
        ),
        migrations.AddField(
            model_name='searchtablechipseq',
            name='mid',
            field=models.IntegerField(db_column='mid', null=True),
        ),
    ]
