# Generated by Django 3.2 on 2021-05-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='circ_disease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assembly', models.CharField(max_length=100)),
                ('chr_num', models.CharField(max_length=50)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('disease', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'circ_disease',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Log2FC', models.FloatField(db_column='Log2FC', null=True)),
                ('p_value', models.FloatField(db_column='p_value', null=True)),
                ('padj', models.FloatField(db_column='padj', null=True)),
                ('minus_log10p', models.FloatField(db_column='minus_log10p', null=True)),
                ('minus_log10padj', models.FloatField(db_column='minus_log10padj', null=True)),
                ('filename', models.CharField(db_column='filename', max_length=255)),
                ('GeneName', models.CharField(db_column='GeneName', max_length=255)),
            ],
            options={
                'db_table': 'CombinedData',
            },
        ),
    ]
