# Generated by Django 3.2 on 2021-06-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_circ_disease_searchtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtable',
            name='CellLine',
            field=models.CharField(db_column='CellLine', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='searchtable',
            name='DataSet',
            field=models.CharField(db_column='DataSet', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='searchtable',
            name='Dose',
            field=models.IntegerField(db_column='Dose', default=''),
        ),
        migrations.AddField(
            model_name='searchtable',
            name='Duration',
            field=models.IntegerField(db_column='Duration', default=''),
        ),
        migrations.AddField(
            model_name='searchtable',
            name='Rep',
            field=models.IntegerField(db_column='Rep', default=''),
        ),
        migrations.AddField(
            model_name='searchtable',
            name='RepL',
            field=models.CharField(db_column='RepL', default='', max_length=255),
        ),
    ]
