# Generated by Django 2.2.3 on 2022-12-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_auto_20220419_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTableMetaRawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gene', models.CharField(db_column='Gene', default='', max_length=255)),
                ('Source', models.CharField(db_column='Source', default='', max_length=255)),
                ('Percentile', models.FloatField(db_column='Percentile', null=True)),
                ('cell_line', models.CharField(db_column='cell_line', default='', max_length=255)),
                ('dose', models.FloatField(db_column='dose', null=True)),
                ('duration', models.FloatField(db_column='duration', null=True)),
                ('duration2', models.FloatField(db_column='duration2', null=True)),
                ('rep', models.IntegerField(db_column='rep', null=True)),
                ('method', models.CharField(db_column='method', default='', max_length=255)),
            ],
            options={
                'db_table': 'MetaRawPercentData',
            },
        ),
    ]
